apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-task-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SunMaungOo/task-runner-application
    targetRevision: HEAD 
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: task-runner
  
  syncPolicy:
    automated: 
      enabled: false 
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true