apiVersion: v1 
kind: ConfigMap
metadata:
  name: auth-cm
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
data:
  AUTH_DB: "auth-db"

---

apiVersion: v1 
kind: Service 
metadata:
  name: auth-mongodb-svc
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterIP: None
  selector:
    app: auth-mongodb
  ports:
    - port: 27017
      name: mongodb-default-port
            
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-mongodb
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  serviceName: auth-mongodb-svc
  selector:
    matchLabels:
      app: auth-mongodb
  replicas: 2 
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
        - name: auth-mongodb
          image: mongo:7.0
          # make it the part of the cluster
          command: ["mongod"]
          args: ["--replSet","rs0","--bind_ip_all"]
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          livenessProbe:
              exec:
                command:
                  - sh
                  - -c
                  - 'mongosh --eval "db.runCommand({ping:1})"'
              periodSeconds: 10
              timeoutSeconds: 5
          readinessProbe:
              exec:
                command:
                  - sh 
                  - -c
                  - 'mongosh --eval "db.runCommand({hello:1})"'
              initialDelaySeconds: 15
              periodSeconds: 10
              timeoutSeconds: 5
            
                     
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 200M

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:7.0
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_PASSWORD
        command:
          - sh 
          - -c
          - |

            HOST0="auth-mongodb-0.auth-mongodb-svc.task-runner.svc.cluster.local:27017"

            HOST1="auth-mongodb-1.auth-mongodb-svc.task-runner.svc.cluster.local:27017"
            
            until mongosh --host "$HOST0" --eval "db.runCommand({ping:1})" &>/dev/null; do
              echo "Waiting for auth-mongodb-0 to accept authorized traffic..."
              sleep 3
            done

            until mongosh --host "$HOST1" --eval "db.runCommand({ping:1})" &>/dev/null; do
              echo "Waiting for auth-mongodb-1 to accept authorized traffic..."
              sleep 3
            done

            if ! mongosh --host "$HOST0" --quiet --eval "rs.status()" &>/dev/null; then

              mongosh --host "$HOST0" --eval " 

                rs.initiate({_id:"rs0",members:[{_id:0,host:"$HOST0"},{_id:1,host:"$HOST1"}]})

              "

              echo "Waiting for node to become primary..."

              sleep 10

              echo "Creating root administrator user..."

              mongosh --host "$HOST0" \
              --eval 'db.getSiblingDB("admin").createUser({user: process.env.MONGO_USER, pwd: process.env.MONGO_PASSWORD, roles: [{role: "root", db: "admin"}]})' \
              -u "$MONGO_INITDB_ROOT_USERNAME" \
              -p "$MONGO_INITDB_ROOT_PASSWORD"

            else
              echo "Replica set already initialized." 
            fi
            
            '
            

