apiVersion: v1 
kind: ConfigMap
metadata:
  name: auth-cm
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
data:
  AUTH_DB: "auth-db"
  init-mongodb.sh: |
    #!/bin/sh

    export HOST0="auth-mongodb-0.auth-mongodb-svc.task-runner.svc.cluster.local:27017"
    export HOST1="auth-mongodb-1.auth-mongodb-svc.task-runner.svc.cluster.local:27017"

    echo "======================================"
    echo "MongoDB initialization"
    echo "======================================"

    echo "Waiting for MongoDB-0..."

    until mongosh \
      --host "$HOST0" \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --quiet \
      --eval 'db.adminCommand({ping:1})' \
      >/dev/null 2>&1
    do
      echo "MongoDB-0 is not accepting authenticated connections..."
      sleep 3
    done

    echo "MongoDB-0 authentication successful."

    echo "Waiting for MongoDB-1..."

    until mongosh \
      --host "$HOST1" \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --quiet \
      --eval 'db.adminCommand({ping:1})' \
      >/dev/null 2>&1
    do
      echo "MongoDB-1 is not accepting authenticated connections..."
      sleep 3
    done

    echo "MongoDB-1 authentication successful."

    echo "Checking replica-set status..."

    if mongosh \
      --host "$HOST0" \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --quiet \
      --eval 'rs.status().ok' \
      >/dev/null 2>&1
    then

      echo "Replica set is already initialized."

    else

      echo "Replica set is not initialized."
      echo "Initializing replica set..."

      mongosh \
        --host "$HOST0" \
        -u "$MONGO_INITDB_ROOT_USERNAME" \
        -p "$MONGO_INITDB_ROOT_PASSWORD" \
        --authenticationDatabase admin \
        --quiet \
        --eval "
          rs.initiate({
            _id: 'rs0',
            members: [
              {
                _id: 0,
                host: '$HOST0'
              },
              {
                _id: 1,
                host: '$HOST1'
              }
            ]
          })
        "

      echo "Replica-set initialization command completed."

    fi

    echo "Waiting for MongoDB-0 to become PRIMARY..."

    until mongosh \
      --host "$HOST0" \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --quiet \
      --eval 'db.hello().isWritablePrimary' \
      2>/dev/null |
      grep -q true
    do
      echo "MongoDB-0 is not PRIMARY yet..."
      sleep 3
    done

    echo "MongoDB-0 is PRIMARY."

    echo "Replica-set members:"

    mongosh \
      --host "$HOST0" \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --quiet \
      --eval '
        rs.status().members.forEach(function(member) {
          print(
            member.name +
            " | " +
            member.stateStr +
            " | health=" +
            member.health
          );
        });
      '

    echo "======================================"
    echo "MongoDB initialization completed."
    echo "======================================"

---

apiVersion: v1 
kind: Service 
metadata:
  name: auth-mongodb-svc
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterIP: None
  selector:
    app: auth-mongodb
  ports:
    - port: 27017
      name: mongodb-default-port
            
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-mongodb
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  serviceName: auth-mongodb-svc
  selector:
    matchLabels:
      app: auth-mongodb
  replicas: 2 
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      # allow mongodb to read key file
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: auth-mongodb
          image: mongo:7.0
          # make it the part of the cluster
          args: ["--replSet","rs0","--bind_ip_all","--keyFile","/opt/mongodb/mongodb-keyfile"]
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: keyfile
              mountPath: /opt/mongodb
              readOnly: true
          livenessProbe:
              exec:
                command:
                  - sh
                  - -c
                  - 'mongosh --eval "db.runCommand({ping:1})"'
              periodSeconds: 10
              timeoutSeconds: 5
          readinessProbe:
              exec:
                command:
                  - sh 
                  - -c
                  - 'mongosh --eval "db.runCommand({hello:1})"'
              initialDelaySeconds: 15
              periodSeconds: 10
              timeoutSeconds: 5
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-mongodb
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mongodb
                  key: MONGO_INITDB_ROOT_PASSWORD
              

      initContainers:
        - name: auth-mongodb-init
          image: mongo:7.0
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: 
            - sh
            - -c
            - | 
              echo "Copying MongoDB keyfile"
              cp /secret/mongodb-keyfile /opt/mongodb/mongodb-keyfile
              echo "Setting ownership"
              chown 999:999 /opt/mongodb/mongodb-keyfile
              echo "Setting permissions"
              chmod 400 /opt/mongodb/mongodb-keyfile
              echo "Checking keyfile"
              ls -ln /opt/mongodb/mongodb-keyfile
          volumeMounts:
            - name: keyfile-secret
              mountPath: /secret
              readOnly: true

            - name: keyfile
              mountPath: /opt/mongodb

      volumes:
        - name: keyfile-secret
          secret:
            secretName: auth-mongodb
            defaultMode: 0400
            items:
              - key: MONGO_KEY_FILE_DATA
                path: mongodb-keyfile
        - name: keyfile
          emptyDir: {}
                     
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 200M

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:7.0
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_PASSWORD
        command:
          - sh
          - /scripts/init-mongodb.sh
        volumeMounts:
          - name: auth-config
            mountPath: /scripts/init-mongodb.sh
            subPath: init-mongodb.sh
            readOnly: true
      
      volumes:
        - name: auth-config
          configMap:
            name: auth-cm
            defaultMode: 0555

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: task-runner
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: myapp
        image: sunmaungoo/task-runner-auth:afe74b4
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: auth-cm
                key: AUTH_DB

          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_USERNAME

          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-mongodb
                key: MONGO_INITDB_ROOT_PASSWORD

          - name: MONGO_URI
            value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@auth-mongodb-svc:27017/$(MONGO_INITDB_DATABASE)?authSource=admin&replicaSet=rs0"

          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-svc
                key: JWT_SECRET

